### ISSUE TITLE
AtCoder's Japanese homepage is not compatible with the dark mode

### ISSUE THREAD

**Issue by hellolin-oi** [beijixiaohu/OJBetter#4]
https://atcoder.jp/?lang=ja

After enabling the dark mode, I noticed that certain elements like `#header`, `.m-box_inner`, and `.m-list-job_inner` on the page have white backgrounds that are not properly adjusted. This affects the overall visual experience to some extent.

Btw, I think the `.html2md-panel` element (MarkDown 视图, Copy, 翻译) should not be displayed on the homepage. Is there a way to hide it?

**Comment by beijixiaohu** [comment]
Thanks for your feedback! I apologize for forgetting to add dark mode for the Japanese interface. It will be fixed in the next version.

Regarding the display of the `.html2md-panel` on the homepage, it's because these buttons are added using the code below:

```js
// 基本添加
$('section').each(function () {
    let id = "_" + getRandomNumber(8);
    addButtonPanel(this, id, "this_level");
    addButtonWithHTML2MD(this, id, "this_level");
    addButtonWithCopy(this, id, "this_level");
    addButtonWithTranslation(this, id, "this_level");
});
```

Unfortunately, the homepage happens to have a lot of elements with section tags.

To address this issue, I'll consider making a special check for the homepage.
